<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit472c070691b5c70ad81961fcb359cec7
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Fxp\\Composer\\AssetPlugin\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Fxp\\Composer\\AssetPlugin\\' => 
        array (
            0 => __DIR__ . '/..' . '/fxp/composer-asset-plugin',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit472c070691b5c70ad81961fcb359cec7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit472c070691b5c70ad81961fcb359cec7::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
